apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigsystem-vue
  namespace: test
  labels:
    app: bigsystem-vue
spec:
  replicas: 2
  selector:
    matchLabels: { app: bigsystem-vue }
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels: { app: bigsystem-vue }
    spec:
      containers:
        - name: bigsystem-vue
          env:
            - name: bigsystem-vue
              valueFrom:
                fieldRef: { fieldPath: metadata.name }
          image: hub.harbor.com/library/kgf-vue:v1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 0.4
              memory: 256Mi